[project]
name = "themeswitcher"
version = "1.0.0"
description = "A config and theme manager for Hyprland"
requires-python = ">=3.14"

dependencies = ["platformdirs"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
